apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.postgres.pvcSize }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.mongodb.pvcSize }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: publisher-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.publisher.pvcSize }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: superdesk-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.superdesk.pvcSize }}
